server:
  port: ${APPLICATION_PORT:8080}

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${APP_DB_URL:localhost}:${APP_DB_PORT:5432}/${APP_DB_NAME:tm_db}
    username: ${APP_DB_USERNAME:postgres}
    password: ${APP_DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    openInView: false
    show_sql: true
    generate-ddl: true
  data:
    jpa:
      repositories.enabled: true

frontend:
  url: ${FRONTEND_API_URL:"http://localhost:4200"}
